### ISSUE TITLE
Did you try SD card : sd_MMC 1-bit mode??

### ISSUE THREAD

**Issue by JohnTaipei** [moononournation/MiniTV#1]
Hello:
Did you try SD card : SD_MMC 1-bit mode??

i try SPIFFS and SPI SD mode
it works well
but sd_MMC 1-bit mode failed (esp32 core V2.0.3 & V2.0.4)
==>"ERROR: File system mount failed!"

Thanks

**Comment by moononournation** [comment]
Yes, I also tested failed. So I mentioned fallen back using SD library in my instructables.

**Comment by JohnTaipei** [comment]
i see
thanks

because i want to use esp32-cam micro sd slot
run 1-bit mode
add a st7789 24x320 lcd to play video

try your sd_benchmark code
esp32-cam + 1-bit mode:
V1.0.4 works well
V2.0.3 & V2.0.4 failed
so i asked espressif this question

at V1.0.4
try to compile your miniTV code
but compile failed

**Comment by moononournation** [comment]
Actually cannot use SD_MMC is not a big concern. The bottle neck is MJPEG decode.
